"""
Forensics Lab — Compliance Report System style
WHO: AML Investigators, Auditors
WHAT: "What's the evidence?" — Detection comparison, model analysis, research findings
LINKS TO: Performance (model details), Executive (back to overview)

DATA SOURCE: All metrics from real experiment results (ablation, case_study JSON files).
"""

import streamlit as st
import plotly.graph_objects as go
import pandas as pd
import numpy as np
from datetime import datetime

from _lib.i18n import t


def _generate_sar_pdf(cs, abl):
    """Generate a SAR (Suspicious Activity Report) PDF using real experiment data only."""
    try:
        from fpdf import FPDF
    except ImportError:
        return None

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Header
    pdf.set_fill_color(10, 14, 23)
    pdf.rect(0, 0, 210, 40, 'F')
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(0, 212, 170)
    pdf.set_y(10)
    pdf.cell(0, 10, "ChainGuard", ln=True, align="C")
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(200, 200, 200)
    pdf.cell(0, 8, "Detection Analysis Report", ln=True, align="C")

    pdf.ln(10)

    # Report metadata
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Report Details", ln=True)
    pdf.set_draw_color(0, 212, 170)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    pdf.set_font("Helvetica", "", 10)
    now = datetime.now()
    meta = [
        ("Date", now.strftime("%Y-%m-%d %H:%M:%S")),
        ("Generated By", "ChainGuard Fraud Detection Platform"),
        ("Model Version", "TH-GNN M3 (R-GCN + Heterogeneous Edges)"),
        ("Dataset", "Elliptic Bitcoin Transaction Dataset"),
        ("Evaluation", "Temporal split: train TS1-34, val TS35-41, test TS42-49"),
    ]
    for label, value in meta:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(50, 7, f"{label}:", ln=False)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, value, ln=True)

    pdf.ln(5)

    # Summary Section
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Detection Summary (Real Experiment Results)", ln=True)
    pdf.set_draw_color(0, 212, 170)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    pdf.set_font("Helvetica", "", 10)
    total = cs["total_illicit_test"]
    both = cs["both_detect"]
    m3_only = cs["m3_only"]
    gcn_only = cs["gcn_only"]
    neither = cs["neither"]
    total_detected = both + m3_only

    summary_lines = [
        f"Total illicit transactions in test set (TS 42-49): {total}",
        f"Detected by TH-GNN (M3): {total_detected} ({total_detected/total:.1%})",
        f"Detected by both TH-GNN and GCN: {both}",
        f"Uniquely detected by TH-GNN: {m3_only}",
        f"Uniquely detected by GCN: {gcn_only}",
        f"Undetected by any model: {neither} ({neither/total:.1%})",
        f"High confidence (TH-GNN, >0.9): {cs['m3_high_conf']}",
        f"High confidence (GCN, >0.9): {cs['gcn_high_conf']}",
    ]
    for line in summary_lines:
        pdf.cell(0, 6, f"  - {line}", ln=True)

    pdf.ln(5)

    # Model Comparison Table
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Ablation Study Results", ln=True)
    pdf.set_draw_color(0, 212, 170)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 9)
    col_widths = [50, 28, 28, 28, 28]
    headers = ["Model", "AUC-ROC", "F1", "Precision", "Recall"]
    for w, h in zip(col_widths, headers):
        pdf.cell(w, 7, h, border=1, align="C")
    pdf.ln()

    pdf.set_font("Helvetica", "", 9)
    model_names = {
        "M1": "M1: GCN Baseline",
        "M2": "M2: +Temporal Attention",
        "M3": "M3: R-GCN +Hetero (Best)",
        "M4": "M4: Full TH-GNN",
        "M5": "M5: +Label Propagation",
    }
    for key, name in model_names.items():
        m = abl[key]
        vals = [name, f"{m['auc_roc']:.4f}", f"{m['f1']:.4f}",
                f"{m['precision']:.4f}", f"{m['recall']:.4f}"]
        for w, v in zip(col_widths, vals):
            pdf.cell(w, 6, v, border=1, align="C")
        pdf.ln()

    pdf.ln(5)

    # Key Findings
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Key Findings", ln=True)
    pdf.set_draw_color(0, 212, 170)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    best = abl["M3"]
    gcn = abl["M1"]
    auc_delta = (best["auc_roc"] - gcn["auc_roc"]) / gcn["auc_roc"]

    pdf.set_font("Helvetica", "", 10)
    findings = [
        f"TH-GNN (M3) achieves AUC-ROC of {best['auc_roc']:.4f}, +{auc_delta:.1%} over GCN baseline.",
        f"M3 uniquely detects {m3_only} illicit transactions ({m3_only/total:.1%}) missed by GCN.",
        f"Graph augmentation (temporal k-NN) contributes more than model complexity: M3 > M4 > M5.",
        f"Without augmentation, GCN (0.7449) underperforms Random Forest (0.8601).",
        f"Temporal k-NN edges connect isolated timesteps, enabling cross-time information flow.",
    ]
    for line in findings:
        pdf.cell(0, 6, f"  - {line}", ln=True)

    pdf.ln(8)

    # Footer
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 5, "This report contains only real experiment results from the ChainGuard platform.", ln=True, align="C")
    pdf.cell(0, 5, "NYU Tandon School of Engineering | MS Thesis 2026", ln=True, align="C")

    return bytes(pdf.output())


def render(DATA, navigate_to):
    cs = DATA["case_study"]
    abl = DATA["ablation"]

    if st.session_state.get("drill_from"):
        st.markdown(f'<div class="breadcrumb">\u2190 from {st.session_state["drill_from"]}</div>', unsafe_allow_html=True)

    st.markdown(f"# {t('forensics_title')}")
    st.markdown(t("forensics_subtitle"))
    st.markdown("---")

    tab1, tab2, tab3 = st.tabs([t("detection_evidence"), t("ablation_analysis"), t("research_conclusions")])

    with tab1:
        st.markdown(f"### {t('detection_comparison')}")

        total = cs["total_illicit_test"]
        both, m3_only, gcn_only, neither = cs["both_detect"], cs["m3_only"], cs["gcn_only"], cs["neither"]

        # Venn diagram
        fig = go.Figure()
        fig.add_shape(type="circle", x0=-1.5, y0=-1.5, x1=1.5, y1=1.5,
                      line=dict(color="#3B82F6", width=2), fillcolor="rgba(33,150,243,0.1)")
        fig.add_shape(type="circle", x0=-0.5, y0=-1.5, x1=2.5, y1=1.5,
                      line=dict(color="#00D4AA", width=2), fillcolor="rgba(100,255,218,0.1)")
        fig.add_annotation(x=-0.8, y=0, text=f"<b>GCN Only</b><br>{gcn_only}", font=dict(color="#3B82F6", size=16), showarrow=False)
        fig.add_annotation(x=0.5, y=0, text=f"<b>Both</b><br>{both}", font=dict(color="#E5E7EB", size=18), showarrow=False)
        fig.add_annotation(x=1.7, y=0, text=f"<b>TH-GNN</b><br><b>{m3_only}</b>", font=dict(color="#00D4AA", size=15), showarrow=False)
        fig.add_annotation(x=0.5, y=-2.2, text=f"{t('undetected')}: {neither} ({neither/total:.0%})", font=dict(color="#EF4444", size=13), showarrow=False)
        fig.update_layout(height=300, xaxis=dict(range=[-2.5, 4.0], showgrid=False, zeroline=False, showticklabels=False),
                          yaxis=dict(range=[-2.8, 2], showgrid=False, zeroline=False, showticklabels=False, scaleanchor="x"),
                          paper_bgcolor="rgba(0,0,0,0)", margin=dict(l=20, r=20, t=20, b=20))
        st.plotly_chart(fig, use_container_width=True)

        e1, e2, e3, e4 = st.columns(4)
        e1.metric(t("thgnn_total"), f"{both + m3_only}", f"+{m3_only} unique")
        e2.metric(t("gcn_total"), f"{both + gcn_only}")
        e3.metric(t("high_conf_thgnn"), f"{cs['m3_high_conf']}", f"vs {cs['gcn_high_conf']} GCN")
        e4.metric(t("undetected"), f"{neither}", f"{neither/total:.0%} gap")

        st.markdown(f'<div class="risk-low"><strong style="color:#00D4AA">{t("evidence_text")}</strong><br>'
                    f'<span style="color:#E5E7EB">{t("evidence_detail").format(m3_only=m3_only, pct=f"{m3_only/total:.0%}")}</span></div>', unsafe_allow_html=True)

        st.caption(t("evidence_source_caption"))

        if st.button(f"\U0001f9ea {t('model_details')}", key="ev_to_perf"):
            navigate_to("Performance"); st.rerun()

    with tab2:
        st.markdown(f"### {t('ablation_component_contributions')}")
        st.caption(t("ablation_caption"))

        # Ablation bar chart
        models = ["M1", "M2", "M3", "M4", "M5"]
        model_names = {
            "M1": "GCN Baseline",
            "M2": "+Temporal Attention",
            "M3": "+Hetero Edges (Best)",
            "M4": "Full TH-GNN",
            "M5": "+Label Propagation",
        }
        aucs = [abl[m]["auc_roc"] for m in models]
        f1s = [abl[m]["f1"] for m in models]
        precisions = [abl[m]["precision"] for m in models]
        recalls = [abl[m]["recall"] for m in models]

        fig_abl = go.Figure()
        fig_abl.add_trace(go.Bar(name="AUC-ROC", x=[model_names[m] for m in models], y=aucs,
                                  marker_color="#00D4AA", text=[f"{v:.4f}" for v in aucs], textposition="outside"))
        fig_abl.add_trace(go.Bar(name="F1", x=[model_names[m] for m in models], y=f1s,
                                  marker_color="#3B82F6", text=[f"{v:.4f}" for v in f1s], textposition="outside"))
        fig_abl.update_layout(height=350, barmode="group",
                              paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(17,24,39,0.5)",
                              font=dict(color="#E5E7EB"), margin=dict(l=40, r=20, t=30, b=60),
                              yaxis=dict(range=[0, 1], gridcolor="rgba(75,85,99,0.3)", color="#9CA3AF"),
                              xaxis=dict(color="#9CA3AF"),
                              legend=dict(font=dict(color="#E5E7EB")))
        st.plotly_chart(fig_abl, use_container_width=True)

        # Delta analysis
        st.markdown(f"#### {t('component_contribution_delta')}")
        for m in ["M2", "M3", "M4", "M5"]:
            delta = abl[m]["auc_roc"] - abl["M1"]["auc_roc"]
            pct = delta / abl["M1"]["auc_roc"]
            color = "#10B981" if delta > 0 else "#EF4444"
            st.markdown(
                f'<div class="stat-row">'
                f'<span style="color:#E5E7EB">{model_names[m]}</span>'
                f'<span style="color:{color}; font-family:JetBrains Mono,monospace">'
                f'{"+%.4f" % delta} ({"+%.1f%%" % (pct * 100)})</span>'
                f'</div>', unsafe_allow_html=True)

        # Detailed metrics table
        st.markdown(f"#### {t('full_metrics_table')}")
        df = pd.DataFrame([{
            "Model": model_names[m],
            "AUC-ROC": f"{abl[m]['auc_roc']:.4f}",
            "F1": f"{abl[m]['f1']:.4f}",
            "Precision": f"{abl[m]['precision']:.4f}",
            "Recall": f"{abl[m]['recall']:.4f}",
        } for m in models])
        st.dataframe(df, use_container_width=True, hide_index=True)

    with tab3:
        st.markdown(f"### {t('key_research_findings')}")

        findings = [
            (t("finding_augmentation_title"),
             t("finding_augmentation_body"),
             f"M3: {abl['M3']['auc_roc']:.4f} > M4: {abl['M4']['auc_roc']:.4f} > M5: {abl['M5']['auc_roc']:.4f}"),
            (t("finding_isolated_title"),
             t("finding_isolated_body"),
             f"GCN: {abl['M1']['auc_roc']:.4f} < RF: 0.8601"),
            (t("finding_beats_title"),
             t("finding_beats_body"),
             f"TH-GNN: {abl['M3']['auc_roc']:.4f} > GraphSAGE: 0.8624 > RF: 0.8601"),
        ]
        for title, body, evidence in findings:
            st.markdown(f"<div style='background:rgba(255,255,255,0.03); border-radius:8px; padding:16px; margin:10px 0'>"
                        f"<h4 style='color:#00D4AA; margin:0'>{title}</h4>"
                        f"<p style='color:#E5E7EB; margin:8px 0'>{body}</p>"
                        f"<p style='color:#F59E0B; font-size:0.85rem; margin:0'>{t('evidence_label')}: {evidence}</p></div>", unsafe_allow_html=True)

        st.caption(t("findings_caption"))

        st.markdown('<div style="background:rgba(100,255,218,0.05); border-radius:12px; padding:24px; text-align:center; margin-top:20px">'
                    '<h3 style="color:#00D4AA; margin:0">ChainGuard</h3>'
                    '<p style="color:#E5E7EB">Cross-Chain Cryptocurrency Fraud Detection using TH-GNN</p>'
                    '<p style="color:#9CA3AF">NYU Tandon - MS Thesis 2026</p>'
                    f'<p style="color:#00D4AA; font-size:1.2rem">AUC: {abl["M3"]["auc_roc"]:.4f} | '
                    f'+{(abl["M3"]["auc_roc"]-abl["M1"]["auc_roc"])/abl["M1"]["auc_roc"]:.1%} vs baseline</p></div>',
                    unsafe_allow_html=True)

        st.markdown("")
        if st.button(f"\U0001f4ca {t('back_to_executive')}", key="conc_to_exec", type="primary"):
            navigate_to("Executive"); st.rerun()

    # ── PDF Report Generation ──
    st.markdown("---")
    st.markdown(f"### {t('generate_sar')}")
    st.caption(t("report_contains_real"))

    try:
        import fpdf  # noqa: F401
        fpdf_available = True
    except ImportError:
        fpdf_available = False

    if not fpdf_available:
        st.warning(t("fpdf_missing"))
        st.code("pip install fpdf2", language="bash")
    else:
        pdf_bytes = _generate_sar_pdf(cs, abl)
        if pdf_bytes is not None:
            now = datetime.now()
            st.download_button(
                label=f"\U0001f4c4 {t('sar_download')}",
                data=pdf_bytes,
                file_name=f"ChainGuard_Report_{now.strftime('%Y%m%d')}.pdf",
                mime="application/pdf",
                key="download_sar",
            )
        else:
            st.error(t("fpdf_missing"))
